CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat BIGINT                                  NOT NULL,
    lon BIGINT                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    pinned BOOLEAN                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    annotation        VARCHAR(512)                            NOT NULL,
    category_id       BIGINT                                  NOT NULL,
    paid              BOOLEAN                                 NOT NULL,
    eventDate         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id      BIGINT                                  NOT NULL,
    views             BIGINT                                  NOT NULL,
    confirmedRequests BIGINT                                  NOT NULL,
    state             VARCHAR(255)                            NOT NULL,
    createdOn         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    publishedOn       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location_id       BIGINT                                  NOT NULL,
    requestModeration BOOLEAN                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS events_list
(
    COMPILATION_ID BIGINT NOT NULL,
    EVENTS_ID      BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS events_list_compilation_id_events_id_index
    ON events_list (COMPILATION_ID, EVENTS_ID);